# Generated by Django 5.2.11 on 2026-02-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apartamento', models.CharField(max_length=10)),
                ('bloco', models.CharField(max_length=5)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_entrada', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
